server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/short_link
    username: postgres
    password: Sobirov0717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secretKey: '03d2430e18744da8db2b8dbd64a64977be5c1a7f06d52197c9b8113a3b552c69'
    expireDays: 7